### ISSUE TITLE
refactor to minimize duplication (and lag distance) from nixpkgs

### ISSUE THREAD

**Issue by colemickens** [nix-community/nixpkgs-wayland#266]
Most package derivations were copied from nixpkgs. This is bad because we're duplicating code, we're missing the enhancements landing in nixpkgs, etc. Further, some things are changing with how sway is patched upstream, and interacts with swaybg, and it would be unfortunate if we didn't also reflect that.

So, this issue is to track replacing most of the `pkgs/**/default.nix`  so that they override the `src` attribute of their sister-attribute in nixpkgs.

This won't affect any packages that don't (yet) exist in nixpkgs, nor any packages who require additional changes to the derivation (this can be because of a project changing build tools between releases, etc).

**Comment by berbiche** [comment]
> could you explain what this does?
> 
> ```
>   ignore = [ "waybar" ];
>   args = lib.filterAttrs (n: v: (!builtins.elem n ignore)) args_;
> ```

At a quick glance, the module allows passing extra parameters to `waybar.override`.

Because these extra parameters are also used to pass the base waybar package, it needs to be removed as its not accepted by waybar's override (can be inspected with `builtins.functionArgs waybar.override`).

The `filterAttrs` logic can be rewritten to the simpler `builtins.removeAttrs args_ [ "waybar" ]` to achieve the same result.

**Comment by Artturin** [comment]
> The `filterAttrs` logic can be rewritten to the simpler `builtins.removeAttrs args_ [ "waybar" ]` to achieve the same result.

thanks

this issue will be fixed by https://github.com/nix-community/nixpkgs-wayland/pull/360
