### ISSUE TITLE
cage doesn't compile

### ISSUE THREAD

**Issue by Artturin** [nix-community/nixpkgs-wayland#294]
https://github.com/Hjdskes/cage/pull/191

**Comment by colemickens** [comment]
Hm, if this slipped into the repo, it's likely because of an aggressive rebase/push script that I have that keeps pushing this repo when I shouldn't.

I'm trying to figure out a branch protection solution, but GH gives options that are fairly limiting (for example, I need a way for the bot account to be able to push without a PR).

**Comment by Artturin** [comment]
i didn't mean it doesn't compile in this repo 

the pr is merged now so we just need to wait for https://nixpk.gs/pr-tracker.html?pr=127897 to be in nixos-unstable or unpin its wlroots
