### ISSUE TITLE
pkg request: wl-gammarelay-rs: dbus gamma service in rust

### ISSUE THREAD

**Issue by colemickens** [nix-community/nixpkgs-wayland#375]
see: https://github.com/MaxVerevkin/wl-gammarelay-rs

**Comment by ibrahimkettaneh** [comment]
I would like to add that wl-gammarelay-rs serves a valuable purpose for accessibility in Wayland window managers. Outside of KDE and Gnome's desktop environments, it is the only solution I have found to invert the screen on Wayland.

I have looked into wl-gammactl and wlsunset which are already packaged, but they cannot invert the screen. If alternatives solutions exist on NixOS I would be happy to use them, but this is the only solution I currently know of, so I see this as a valuable package to add to enhance accessibility of NixOS.

I would be happy to provide any further information on this tool, and look forward to hearing from you.

**Comment by ibrahimkettaneh** [comment]
Hi @colemickens , do we just wait for someone maintaining the package repository to let us know if they'll package `wl-gammarelay-rs`? I am asking because it appears that you and I are the only people following this issue. I would greatly appreciate if you let me know how I could express that there's some interest in them packaging this one, especially because it helps with accessibility.

I also wanted to say thank you for your contributions to the nix community :)

**Comment by Artturin** [comment]
https://github.com/nix-community/nixpkgs-wayland/commit/57ec6ff76400d6f9debf98fa7feb809f7755a076
