### ISSUE TITLE
wlroots fails to build

### ISSUE THREAD

**Issue by NotAShelf** [nix-community/nixpkgs-wayland#403]
I initially thought this was an issue with nixpkgs, however, upon removing nixpkgs-wayland from my inputs and removing the overlay the build failure has been resolved.

The issue is mostly documented here: https://github.com/NixOS/nixpkgs/issues/226328

**Comment by NotAShelf** [comment]
The key here seems to be using the overlay.

**Comment by colemickens** [comment]
Hi @NotAShelf, the CI for this repository ensures that our updated wlroots/ builds against nixos-unstable. You might be having an issue that gamescope requires an OLDER version of wlroots than this overlay provides.

I have stopped using this repo as an overlay, partially due to this. I also once had a patch for gamescope to force it to use a versioned wlroots, but I sort of  "gave up" on Linux gaming for now, so I lost track of it. Someone else was working on getting newer gamescope building, not sure if you already found them and tagged them.

One approach might be to add gamescope here, too, and keep it updated, but it was a moving target and I don't have time to maintain something else that requires that much time/attention.

**Comment by colemickens** [comment]
To elaborate a bit, I still *use* this repository, but I manually pull in whatever packages I need. In particular:

https://github.com/colemickens/nixcfg/blob/cdd7e712c27d2eef989e9d62a08417d605de9dfc/profiles/gui-sway.nix#L108-L113

So, I guess I do still use an overlay (though I could set the sway package, and then probably just overlay the wlr portal...)

**Comment by NotAShelf** [comment]
Hmm. So I would need to remove the overlay and pull gamescope frok the pkgset in order to resolve the issue.

**Comment by Artturin** [comment]
if you're using flakes you can just use gamescope from the nixpkgs flake

**Comment by colemickens** [comment]
I think CI is actually not working correctly.

**Comment by colemickens** [comment]
I'm seeing wlroots failure too, the latest version requires wayland newer than is in nixos-unstable right now.

**Comment by colemickens** [comment]
I've force pushed and rolled some updates back, disabled actions for now, fixed up waybar, the packages are all building again. Sorry about this, I'll try to look at the CI soon.

**Comment by Artturin** [comment]
issue is https://github.com/Mic92/nix-build-uncached/issues/52

**Comment by Artturin** [comment]
ah nvm were not using that and we're already using nix-eval-jobs https://github.com/nix-community/nixpkgs-wayland/blob/45e2d3ed33b69ec69d3cc010ee30d2672f8e5fd2/main.nu#L99-L113
